import './global.css';
import { NavBarLayout } from '@/components/common/navbar/Navbar';
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <UserProvider>
        <body>
          <NavBarLayout />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
